# Generated by Django 3.2.9 on 2022-01-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_auto_20220111_2219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
